FROM node:20-alpine

WORKDIR /app

# Install dependencies dulu (layer cache)
COPY package.json package-lock.json* ./
RUN npm install

# Copy semua source
COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]
